import Link from "next/link"
import Head from 'next/head'
import { v4 as uuidv4 } from 'uuid';
import {VscChevronRight, VscChevronDown} from "react-icons/vsc";
import {Footer, range,useModal} from "../../components";
import { f2l } from "../../data";

export const getStaticPaths = async () => {

    const data = f2l()
    
    const paths = Object.values(data).map(i =>{
        return { params: {id: i.id} }
    })

    return {
        paths,
        fallback:false
    }
}

export const getStaticProps = async (context) => {
    
    const key = context.params.id
        
    const data = f2l()

    return {props: {
        algs: data,
        alg: data[key]
    }}
}

function F2LAlgorithm({algs,alg}){

    const {ref, toggled, setToggled} = useModal()

    const Squares = () => range(1,9,1).map(() => <div 
        className="square"
        key={uuidv4()}>
    </div>)

    

    return (
        <div className="container">
             <Head>
                <title>CFOP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div className="title">F2L</div>
                <nav className='header-nav'>
                    <Link href="/cross">Cross</Link>
                    <Link href="/oll">OLL</Link>
                    <Link href="/pll">PLL</Link>
                </nav>
            </header>

            <section>
                <nav className="section-menu" ref={ref}>
                    <div  className={
                        toggled ?`menu-title border-title`:`menu-title`
                    }>
                        <div 
                            className="svg-container"
                        >{ toggled ? 
                            <VscChevronDown 
                                onClick={() => setToggled(!toggled)}
                            /> : 
                            <VscChevronRight 
                                onClick={() => setToggled(!toggled)}
                            />
                        }</div>
                        <div>{alg.desc}</div>
                    </div>

                    {toggled && 
                    <div className="menu-list" >
                        {Object.keys(algs).map(key => 
                        <li key={key} onClick={() => setToggled(false)}>
                            <Link href={`/f2l/${key}`} >{algs[key].desc}</Link> 
                        </li>
                    )}</div>}
                </nav>
                
                <article className="algorithms">
                    {alg.algorithms.map((i,j) =>
                        <div key={j}>
                            <div className="wrapper">
                                <div className={`cube ${i.hand} ${i.name}`}>
                                    <div className="side front">
                                        <Squares />
                                    </div>
                                    <div className="side left">
                                        <Squares />
                                    </div>
                                    <div className="side right">
                                        <Squares />
                                    </div>
                                    <div className="side top">
                                        <Squares />
                                    </div>
                                    <div className="side back"></div>
                                    <div className="side bottom"></div>
                                </div>
                            </div>
                            <div className="alg-name">{i.alg}</div>
                        </div>
                    )}
                </article>
            </section>

            <Footer />
        </div>
    )
}

export default F2LAlgorithm
