import Link from "next/link"
import Head from 'next/head'
import {Footer } from "../../components";
import { f2l } from "../../data";


function F2L(){

    const props = f2l()
 
    return (
        <div className="container">
             <Head>
                <title>CFOP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div className="title">F2L</div>
                <nav className='header-nav'>
                    <Link href="/cross">Cross</Link>
                    <Link href="/oll">OLL</Link>
                    <Link href="/pll">PLL</Link>
                </nav>
            </header>
            <section>
                <ul className="algorithms-menu">{Object.keys(props).map(key => 
                    <li key={key}>
                        <Link 
                            href={`/f2l/${key}`}
                        >{props[key].desc}</Link> 
                    </li>
                )}</ul>
            </section>
          
            <Footer />
        </div>
    )
}

export default F2L