import Head from 'next/head'
import Link from "next/link"


export default function Home() {
    return (
        <div className="container">
            <Head>
                <title>CFOP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div className="title">
                    CFOP Method
                </div>
            </header>

            <section>
                <p>A method used to solve a 3x3x3 Rubik's Cube.</p>
                <ol>
                    <li><Link href="/cross">Cross</Link>: Solve a cross on the bottom layer.</li>
                    <li><Link href="/f2l">F2L</Link>: Solve the first 2 layers of the cube.</li>
                    <li><Link href="/oll">OLL</Link>: Orient the last layer of the cube.</li>
                    <li><Link href="/pll">PLL</Link>: Permute the last layer of the cube.</li>
                </ol>
            </section>

            <footer>
                &copy; CFOP 2022
            </footer>
        </div>
    )
}
