import Link from "next/link";
import Head from 'next/head';
import { v4 as uuidv4 } from 'uuid';
import {VscChevronRight, VscChevronDown} from "react-icons/vsc";
import { Footer, range, useModal } from "../../components";
import { pll } from "../../data";

export const getStaticPaths = async () => {

    const data = pll()
    
    const paths = Object.values(data).map(i =>{
        return {
            params: {id: i.id}
        }
    })

    return {
        paths,
        fallback:false
    }
}

export const getStaticProps = async (context) => {
    
    const key = context.params.id
    
    const data = pll()
    
    return {props: {
        algs: data,
        alg: data[key]
    }}
    
}

function PLLAlgorithm({algs,alg}){

    const {ref, toggled, setToggled} = useModal()

    const Squares = () => range(1,9,1).map(() => <div 
        className="pll-square"
        key={uuidv4()}>
    </div>)
    
    const Strips = ({name}) => range(1,3,1).map(() => <div 
        className={`pll-strips ${name}`}
        key={uuidv4()}>
    </div>)

    return (
        <div className="container">
            <Head>
                <title>CFOP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div className="title">PLL</div>
                <nav className='header-nav'>
                    <Link href="/cross">Cross</Link>
                    <Link href="/f2l">F2L</Link>
                    <Link href="/oll">OLL</Link>
                </nav>
            </header>

            <section>
                <nav className="section-menu" ref={ref}>
                    <div className={
                        toggled ?`menu-title border-title`:`menu-title`
                    }>
                        <div 
                            className="svg-container"
                        >{ toggled ? 
                            <VscChevronDown 
                                onClick={() => setToggled(!toggled)}
                            /> : 
                            <VscChevronRight 
                                onClick={() => setToggled(!toggled)}
                            />
                        }</div>
                        <div>{alg.desc}</div>
                    </div>

                    {toggled && 
                    <div className="menu-list">
                        {Object.keys(algs).map(key => 
                        <li key={key} onClick={() => setToggled(false)}>
                            <Link href={`/pll/${key}`} >{algs[key].desc}</Link> 
                        </li>
                    )}</div>}
                </nav>
                
                <article className="algorithms">
                    {alg.algorithms.map((i,j) =>
                        <div key={j} className="pll-cube">
                            <div className="pll-grid-wrapper">
                                <div className={`pll-top-strip strip`}>
                                    <Strips name={i.name}/>
                                </div>
                                <div className={`pll-right-strip strip`}>
                                    <Strips name={i.name}/>
                                </div>
                                <div className={`pll-bottom-strip strip`}>
                                    <Strips name={i.name}/>
                                </div>
                                <div className={`pll-left-strip strip`}>
                                    <Strips name={i.name}/>
                                </div>
                                <div className={`pll-cube-face ${i.name}`}>
                                    <Squares />
                                </div>
                            </div>
                            <div className="alg-name">{i.alg}</div>
                        </div>
                    )}
                </article>
            </section>

            <Footer />
        </div>
    )
}

export default PLLAlgorithm
