import Link from "next/link"
import Head from 'next/head'
import {Footer} from "../../components";
import { oll } from "../../data";



function OLL(){

    const props = oll()
    
    return (
        <div className="container">
             <Head>
                <title>CFOP</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div className="title">OLL</div>
                <nav className='header-nav'>
                    <Link href="/cross">Cross</Link>
                    <Link href="/f2l">F2L</Link>
                    <Link href="/pll">PLL</Link>
                </nav>
            </header>
            
             <section>
                <ul className="algorithms-menu">{Object.keys(props).map(key => 
                    <li key={key}>
                        <Link 
                            href={`/oll/${key}`}
                        >{props[key].desc}</Link> 
                    </li>
                )}</ul>
            </section>

           <Footer />

        </div>
    )
}

export default OLL

